-- 013_movimientos.sql — Corazón del sistema (plan §5.7). Sin soft-delete: el ciclo de
-- vida vive en la máquina de estados (§6); COMPLETADO/CANCELADO son finales.
-- La restricción de no-traslape (§5.7) se valida en backend dentro de transacción con
-- bloqueo; el índice (unidad_id, fecha_salida, fecha_fin_estimada) la soporta.
CREATE TABLE movimientos (
    id                       BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    unidad_id                BIGINT UNSIGNED NOT NULL,
    piloto_id                BIGINT UNSIGNED NULL,
    ruta_id                  BIGINT UNSIGNED NULL,
    ruta_custom_origen       VARCHAR(150)    NULL,
    ruta_custom_destino      VARCHAR(150)    NULL,
    pais_origen_id           BIGINT UNSIGNED NOT NULL,
    pais_destino_id          BIGINT UNSIGNED NOT NULL,
    tipo_ruta                ENUM('NACIONAL','INTERNACIONAL') NOT NULL,
    fecha_salida             DATETIME        NOT NULL,
    fecha_fin_estimada       DATETIME        NOT NULL,
    fecha_fin_real           DATETIME        NULL,
    referencia_cw            VARCHAR(120)    NULL,
    retorno_disponible       TINYINT(1)      NOT NULL DEFAULT 0,
    pais_solicita_retorno_id BIGINT UNSIGNED NULL,
    estado                   ENUM('RESERVADO','PROGRAMADO','EN_TRANSITO','COMPLETADO','CANCELADO') NOT NULL,
    motivo_cancelacion       VARCHAR(255)    NULL,
    reservado_para           VARCHAR(150)    NULL,
    notas                    TEXT            NULL,
    created_at               DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by               BIGINT UNSIGNED NULL,
    PRIMARY KEY (id),
    KEY idx_movimientos_unidad_ventana (unidad_id, fecha_salida, fecha_fin_estimada),
    KEY idx_movimientos_estado (estado),
    KEY idx_movimientos_paises (pais_origen_id, pais_destino_id),
    KEY idx_movimientos_retorno (retorno_disponible),
    KEY idx_movimientos_piloto (piloto_id),
    KEY idx_movimientos_ruta (ruta_id),
    KEY idx_movimientos_pais_destino (pais_destino_id),
    KEY idx_movimientos_pais_solicita_retorno (pais_solicita_retorno_id),
    CONSTRAINT fk_movimientos_unidad FOREIGN KEY (unidad_id) REFERENCES unidades (id) ON DELETE RESTRICT,
    CONSTRAINT fk_movimientos_piloto FOREIGN KEY (piloto_id) REFERENCES pilotos (id) ON DELETE RESTRICT,
    CONSTRAINT fk_movimientos_ruta FOREIGN KEY (ruta_id) REFERENCES rutas (id) ON DELETE RESTRICT,
    CONSTRAINT fk_movimientos_pais_origen FOREIGN KEY (pais_origen_id) REFERENCES paises (id) ON DELETE RESTRICT,
    CONSTRAINT fk_movimientos_pais_destino FOREIGN KEY (pais_destino_id) REFERENCES paises (id) ON DELETE RESTRICT,
    CONSTRAINT fk_movimientos_pais_solicita_retorno FOREIGN KEY (pais_solicita_retorno_id) REFERENCES paises (id) ON DELETE RESTRICT,
    CONSTRAINT fk_movimientos_created_by FOREIGN KEY (created_by) REFERENCES usuarios (id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
